[package]
name = "rs-mojave-network-core"
version = "0.1.0"
edition = "2024"

[dependencies]
multiaddr.workspace = true
futures.workspace = true
pin-project.workspace = true

[lints]
workspace = true
